### ISSUE TITLE
Plany poplach 9/6/2023

### ISSUE THREAD

**Issue by MacTEC** [zdenda/kaktus-dobijecka#3]
Dnes mi appka zahlasila bonus za dobití 15-18:00, ale po dobití se bonus nepřipsal. Kaktus stránky žádnou akci na dnešek nezmiňují, takže z nějakého důvodu appka zahlasila neexistující Kaktus akci.

**Comment by zdenda** [comment]
Dobrý den, díky za informaci. Appka čerpá info z [webu Kaktusu](https://github.com/zdenda/kaktus-dobijecka/blob/5a223f8fda55efda826d4f7135b7f03e62a9cb92/backend/src/main/java/eu/zkkn/android/kaktus/backend/CheckServlet.java#L39), kde se informace o dobíječce dnes na chvíli nejspíše objevila, takže se rozeslalo upozornění.
Kaktus pak ale asi dobíječku zrušil a informaci z webu stáhl. S tím bohužel nedokážu nic udělat.

Takže děkuji za nahlášení problému, ale nezbývá mi nic jiného, než ho bez řešení zavřít.

**Comment by MacTEC** [comment]
SMS od kaktusu: 
Ahoj, minuly patek jsme na posledni chvili kvuli technickym problemum dodavatele platebni brany odlozili naplanovanou dobijecku. Protoze se ti ale v dobe od 15 do 18 podarilo kredit dobit, pripiseme ti do dnesni pulnoci bonusovy kredit s platnosti 30 dni, jako by dobijecka byla :) www.mujkaktus.cz/chces-pridat Promin za pripadne neprijemnosti a doufame, ze ti kredit udela radost :) Kaktus

**Comment by zdenda** [comment]
Tak aspoň že se k tomu nakonec postavili čelem
