### ISSUE TITLE
19.8. byla akce na 2x kredit, ale appka ho nezaregistrovala

### ISSUE THREAD

**Issue by MacTEC** [zdenda/kaktus-dobijecka#9]
Poslední dobíjecku mám v appce ze 7.8.
Díky moc

**Comment by zdenda** [comment]
Již je opraveno (https://github.com/zdenda/kaktus-dobijecka/commit/f4eba805214935c11098ff7688c468976d50b999).

Bylo to v serverové části, takže ani není potřeba aktualizovat appku na mobilu.
